### ISSUE TITLE
Could you provide the template for your website?

### ISSUE THREAD

**Issue by heany** [vitthal-bhandari/vitthal-bhandari.github.io#1]
Hi,
I stumbled across your personal website, it is very simple and beautiful. I want to build a personal website like this. Could you provide me with your website template and building manual?
Sorry to bother you and thank you for your help:)

Best,

**Comment by vitthal-bhandari** [comment]
> Hi, I stumbled across your personal website, it is very simple and beautiful. I want to build a personal website like this. Could you provide me with your website template and building manual? Sorry to bother you and thank you for your help:)
> 
> Best,

Hi @heany 

I haven't pushed my latest website code to this repo. I will do it as soon as I find the time. You may use that code directly afterwards.

Best
Vitthal

**Comment by vitthal-bhandari** [comment]
@heany you may check the code now. Extremely sorry for the delay.
